### PR TITLE
Removing models related files

### PR DESCRIPTION
**Pull request by humbleOldSage**
This commit removes the following files as they have been relocated to `e-mission-server` :

1. models.py 
2. clustering.py
3. data_wrangling.py
4. mapping.py

The move is part of reorganization to keep all the models in the server repo and the evaluation code and notebook in this repository.

The changes where these 4 files are  received on e-mission-server is covered by  https://github.com/e-mission/e-mission-server/pull/945 .

### CODE REVIEW

**Comment by humbleOldSage** [comment]
Partially Tested because even though all the files which had changes were tested successfully, not all the notebooks and python files in the repository were tested.

**Comment by humbleOldSage** [comment]
Successfully Tested.

Screenshot 2023-12-05 at 12 57 45 AM

Screenshot 2023-12-05 at 12 59 59 AM

Screenshot 2023-12-05 at 1 00 36 AM

**Comment by shankari** [comment]
@humbleOldSage these are the new results - can you have them side by side with the old results to make it easier to compare and confirm no regressions?

**Comment by humbleOldSage** [comment]
Sure. With the results below, I can confirm no changes in results.

 Successfully Tested.

From Recent run  :
Screenshot 2023-12-05 at 12 57 45 AM


From past runs :

Screenshot 2023-11-16 at 5 53 00 PM


From Recent run  :
Screenshot 2023-12-05 at 12 59 59 AM

From the paper:
Screenshot 2023-12-11 at 11 27 16 PM



From Recent run  :
Screenshot 2023-12-05 at 1 00 36 AM

From the paper:


Screenshot 2023-12-11 at 11 26 57 PM

**Pull request merged**
